// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1pbKSjF9tW2GTHVz6JKiN_-Uyu8mlhdg',
    appId: '1:125446034251:web:71d96e781f542b002acece',
    messagingSenderId: '125446034251',
    projectId: 'smartirregation',
    authDomain: 'smartirregation.firebaseapp.com',
    databaseURL: 'https://smartirregation-default-rtdb.firebaseio.com',
    storageBucket: 'smartirregation.firebasestorage.app',
    measurementId: 'G-8Q8QT31Y56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUfj5kPiOVDdvzTgm231qk7Lq8RrQw2OU',
    appId: '1:125446034251:android:73fd97770dd3f2512acece',
    messagingSenderId: '125446034251',
    projectId: 'smartirregation',
    databaseURL: 'https://smartirregation-default-rtdb.firebaseio.com',
    storageBucket: 'smartirregation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDecQIu1AggtKwXtxQ6cWGgdcGj8yK4JDg',
    appId: '1:125446034251:ios:1486df3079b0e0a52acece',
    messagingSenderId: '125446034251',
    projectId: 'smartirregation',
    databaseURL: 'https://smartirregation-default-rtdb.firebaseio.com',
    storageBucket: 'smartirregation.firebasestorage.app',
    iosClientId: '125446034251-8mh146kkb91v1kpn0jcohj5u4hat0avf.apps.googleusercontent.com',
    iosBundleId: 'com.agnefits.smartirregation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1pbKSjF9tW2GTHVz6JKiN_-Uyu8mlhdg',
    appId: '1:125446034251:web:af8691be398b38cd2acece',
    messagingSenderId: '125446034251',
    projectId: 'smartirregation',
    authDomain: 'smartirregation.firebaseapp.com',
    databaseURL: 'https://smartirregation-default-rtdb.firebaseio.com',
    storageBucket: 'smartirregation.firebasestorage.app',
    measurementId: 'G-QWP81BDDDT',
  );
}
